version: '3'
services:
  # server:
  #   build: server
  #   volumes:
  #     - ./server:/usr/src/app:delegated
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     FLASK_ENV: development
  #   command: flask run --host 0.0.0.0

  # db:
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: quill

  db:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag-playground
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  ollama:
    image: ollama/ollama:0.5.0
    volumes:
      - ollama:/root/.ollama
    ports:
      - '11434:11434'
    command: 'llama3.2'

  clickhouse:
    image: clickhouse/clickhouse-server:24.2.2
    container_name: clickhouse
    environment:
      CLICKHOUSE_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}   
      CLICKHOUSE_USER: ${OPENLIT_DB_USER:-default}                   
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - "9000:9000" 
      - "8123:8123" 

  openlit:
    image: ghcr.io/openlit/openlit:latest
    container_name: openlit
    environment:
      INIT_DB_HOST: clickhouse
      INIT_DB_PORT: 8123
      INIT_DB_DATABASE: ${OPENLIT_DB_NAME:-openlit}
      INIT_DB_USERNAME: ${OPENLIT_DB_USER:-default}
      INIT_DB_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
      SQLITE_DATABASE_URL: file:/app/client/data/data.db
    ports:
      - "3001:3000"
    depends_on:
      - clickhouse
    volumes:
      - openlit-data:/app/client/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.94.0
    container_name: otel-collector
    environment:
      INIT_DB_HOST: clickhouse
      INIT_DB_PORT: 9000
      INIT_DB_DATABASE: ${OPENLIT_DB_NAME:-openlit}
      INIT_DB_USERNAME: ${OPENLIT_DB_USER:-default}
      INIT_DB_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
    ports:
      - "4317:4317" 
      - "4318:4318" 
      - "8888:8888" 
      - "55679:55679" 
    depends_on:
      - clickhouse
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml

  # celery-worker:
  #   build:
  #     dockerfile: celery-worker.Dockerfile
  #   volumes:
  #     - ./:/usr/src/app
  #     - ~/Library/Caches/llama_index:/caches/llama_index
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379
  #     - CELERY_RESULT_BACKEND=redis://redis:6379
  #     - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:postgres@db:5432/quill
  #     - LUNARY_API_URL=http://lunary-backend:3333
  #     - LLAMA_INDEX_CACHE_DIR=/caches/llama_index
  #   extra_hosts:
  #   - "host.docker.internal:host-gateway"
 
volumes:
  pgdata:
  ollama:
  clickhouse-data:
  openlit-data: