"""Add vector column

Revision ID: 1733516500
Revises: 1733510289
Create Date: 2024-12-06 14:21:40.636248

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1733516500"
down_revision: Union[str, None] = "1733510289"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("vectors", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "vectors")
    # ### end Alembic commands ###
